from selenium.webdriver.common.by import By


class LoginPageLocators():
    LANG = (By.CSS_SELECTOR, "input[type='hidden']")
    LOGIN = (By.CSS_SELECTOR, "#login")
    PASSWORD = (By.CSS_SELECTOR, "#password")
    SIGN_IN = (By.CSS_SELECTOR, ".btn")

class MainPageLocators():
    BULLETINS = (By.XPATH, "//span[contains(.,'Bulletins')]")
    BULLETINS_BOARD = (By.XPATH, "//a[contains(.,'Bulletin board')]")
    BULLETINS_LIST = (By.XPATH, "//a[contains(.,'Bulletin list management')]")
    USERS = (By.XPATH, "//a[contains(.,'Users')]")
    ASN = (By.XPATH, "//a[contains(.,'ASN')]")
    PROFILE_DROP = (By.CSS_SELECTOR, ".header__user__login")
    SIGN_OUT = (By.XPATH, "//span[text()=' Sign out ']")

class BulletinPageLocators():
    ADD = (By.CSS_SELECTOR, "a.btn")
    SUBJECT = (By.XPATH, "//label[text()='Subject']/following-sibling::div//input")
    MESSAGE = (By.XPATH, "//label[text()='Message']/following-sibling::div//textarea")
    FILTER_INPUT = (By.XPATH, "//label[text()=' Supplier list ']/following-sibling::div//input[@type='text']")
    FILTER_CHOICE = (By.XPATH, "//span[@class='v-list-item__mask']")
    SUBMIT = (By.XPATH, "//button[@type='submit']")
    ATTACH = (By.CSS_SELECTOR, ".d-none")
    DATE_FROM = (By.XPATH, "//label[text()='Date (UTC)']/following-sibling::div//input")
    DATE_TILL = (By.XPATH, "//label[text()='Valid till (UTC)']/following-sibling::div//input")
    TRASH_BUTTON = (By.CSS_SELECTOR, ".mdi-delete")
    DELETE_BUTTON = (By.XPATH, "//span[text()=' Delete ']")
    ALL_NEW = (By.XPATH, "//div[text()=' All ']")
    SUP01_NEW = (By.XPATH, "//div[text()=' SUP01 ']")
    SUP02_NEW = (By.XPATH, "//div[text()=' SUP02 ']")
    PAST = (By.XPATH, "//span[text()=' Past ']")
    ALL_PAST = (By.XPATH, "//div[text()=' All_old ']")
    SUP01_PAST = (By.XPATH, "//div[text()=' SUP01_old ']")
    SUP02_PAST = (By.XPATH, "//div[text()=' SUP02_old ']")
    PENCIL = (By.CSS_SELECTOR, ".mdi-pencil")
    MESSAGE_EDIT = (By.XPATH, "//label[text()=' Message ']/following-sibling::div//textarea")
    EMPTY_LIST = (By.XPATH, "//div[text()='No data available']")

class UsersPageLocators():
    ADD = (By.XPATH, "//span[text()=' Add ']")
    EMAIL = (By.XPATH, "//label[text()='E-mail']/following-sibling::div//input")
    NAME = (By.XPATH, "//label[text()=' Name ']/following-sibling::div//input")
    ROLES_LIST = (By.XPATH, "//label[text()=' Role ']/following-sibling::div//i")
    GSDB = (By.XPATH, "//label[text()=' GSDB ']/following-sibling::div//input")
    SUBMIT = (By.XPATH, "//button[@type='submit']")
    USERS_LIST = (By.XPATH, "//table/tbody/tr")
    
class ASNPageLocators():
    CREATE = (By.XPATH, "//span[text()=' Create ']")
    UPLOAD = (By.XPATH, "//span[text()=' upload ']")
    CARRIER = (By.XPATH, "//label[text()=' Carrier ']/following-sibling::div//input")
    PLANTLIST = (By.XPATH, "//label[text()=' Plant ']/following-sibling::div//i")
    CONTAINER = (By.XPATH, "//label[text()=' Container number ']/following-sibling::div//input")
    TRANS = (By.XPATH, "//label[text()=' Transportation mode* ']/following-sibling::div//input")
    SHIP_DATE = (By.XPATH, "//label[text()=' Shipping date ']/following-sibling::div//input")
    BOL = (By.XPATH, "//label[text()=' Bill of lading ']/following-sibling::div//input")
    FREIGHT = (By.XPATH, "//label[text()=' Freight bill number ']/following-sibling::div//input")
    NET_WEIGHT = (By.XPATH, "//label[text()=' Net weight, kg ']/following-sibling::div//input")
    GROSS_WEIGHT = (By.XPATH, "//label[text()=' Gross weight, kg ']/following-sibling::div//input")
    CONTRACT = (By.XPATH, "//label[text()=' Contract ']/following-sibling::div//input")
    ADD_PARTS = (By.XPATH, "(//span[text()=' Add '])[1]")
    ADD_PACKS = (By.XPATH, "(//span[text()=' Add '])[2]")
    SUBMIT = (By.XPATH, "//button[text()=' Create ']")
    PARTS_PART = (By.XPATH, "//label[text()=' Part number ']/following-sibling::div//input")
    PARTS_QTY = (By.XPATH, "//label[text()=' Quantity sent ']/following-sibling::div//input")
    PARTS_TOTAL = (By.XPATH, "//label[text()=' Previous total quantity ']/following-sibling::div//input")
    PARTS_UOM = (By.XPATH, "//label[text()=' Единица измерения ']/following-sibling::div//input")
    PARTS_WEIGHT = (By.XPATH, "//label[text()=' Weight, kg ']/following-sibling::div//input")
    PARTS_ORIGIN = (By.XPATH, "//label[text()=' Origin ']/following-sibling::div//input")
    PARTS_SUBMIT = (By.XPATH, "//button[@type='submit']")
    PARTS_CANCEL = (By.XPATH, "//button/span[text()=' Cancel ']")
    PACKS_PART = (By.XPATH, "//label[text()=' Part number ']/following-sibling::div//input")
    PACKS_QTY = (By.XPATH, "//label[text()=' Quantity ']/following-sibling::div//input")
    PACKS_LEVEL3 = (By.XPATH, "//label[text()=' Box serial number (level 3) ']/following-sibling::div//input")
    PACKS_LEVEL2 = (By.XPATH, "//label[text()=' Box serial number (level 2) ']/following-sibling::div//input")
    PACKS_LEVEL1 = (By.XPATH, "//label[text()=' Box serial number (level 1) ']/following-sibling::div//input")
    PACKS_TARE = (By.XPATH, "//label[text()=' Tare unit weight gross, kg ']/following-sibling::div//input")
    PACKS_SUBMIT = (By.XPATH, "//button[@type='submit']")
    PACKS_CANCEL = (By.XPATH, "//button/span[text()=' Cancel ']")

