from selenium.webdriver.common.by import By


class LoginPageLocators():
    LANG = (By.CSS_SELECTOR, "input[type='hidden']")
    LOGIN = (By.CSS_SELECTOR, "#login")
    PASSWORD = (By.CSS_SELECTOR, "#password")
    SIGN_IN = (By.CSS_SELECTOR, ".btn")

class MainPageLocators():
    BULLETINS = (By.XPATH, "//span[contains(.,'Bulletins')]")
    BULLETINS_BOARD = (By.XPATH, "//a[contains(.,'Bulletin board')]")
    BULLETINS_LIST = (By.XPATH, "//a[contains(.,'Bulletin list management')]")
    USERS = (By.XPATH, "//a[contains(.,'Users')]")
    ASN = (By.XPATH, "//a[contains(.,'ASN')]")
    PROFILE_DROP = (By.CSS_SELECTOR, ".header__user__login")
    SIGN_OUT = (By.XPATH, "//span[text()=' Sign out ']")
    VERSIONS = (By.XPATH, "//span[contains(.,'Versions')]")
    SUPPLIERS = (By.XPATH, "//span[contains(.,'Suppliers')]")
    ROLES = (By.XPATH, "//span[contains(.,'Roles')]")
    EMAILS = (By.XPATH, "//span[contains(.,'Emails')]")
    EMAIL_ARCHIVE = (By.XPATH, "//a[contains(.,'E-mail archive')]")
    EMAIL_TEMPLATES = (By.XPATH, "//a[contains(.,'Templates')]")
    LOGS = (By.XPATH, "//span[contains(.,'Logs')]")
    ORDERS = (By.XPATH, "//span[contains(.,'Orders')]")
    ORDERS_BY_DAY = (By.XPATH, "//a[contains(.,' Orders grouped by day ')]")
    NEAREST = (By.XPATH, "//a[contains(.,' Nearest shipment date ')]")
    NEAREST_BY_SUPP = (By.XPATH, "//a[contains(.,' Nearest shipment by supplier ')]")
    TWELVE_BY_PART = (By.XPATH, "//a[contains(.,' 12 months reports by part ')]")
    TWELVE_BY_PARTS = (By.XPATH, "//a[contains(.,' 12 months reports by parts ')]")
    HISTORY_14 = (By.XPATH, "//a[contains(.,' History for a part by days with a horizon of 14 days and with a running total ')]")
    HISTORY_17 = (By.XPATH, "//a[contains(.,' History for a part by weeks with a horizon of 17 weeks and with a running total ')]")
    CORRECTIONS = (By.XPATH, "//a[contains(.,' List of order corrections ')]")
    AS_ORDERS = (By.XPATH, "//span[contains(.,'AS orders')]")
    REPORTS = (By.XPATH, "//span[contains(.,'Reports')]")
    TRANSACTIONS = (By.XPATH, "//a[contains(.,' Transactions ')]")
    TURNOVER = (By.XPATH, "//a[contains(.,' Turnover ')]")
    BALANCE = (By.XPATH, "//a[contains(.,' Balance ')]")
    FORECASTS = (By.XPATH, "//a[contains(.,' Forecasts ')]")
    PARTS_PROPERTIES = (By.XPATH, "//a[contains(.,' Parts properties ')]")
    NEW_PARTS = (By.XPATH, "//a[contains(.,' New parts ')]")
    MISSING_PARTS = (By.XPATH, "//a[contains(.,' Missing parts ')]")
    LABELS = (By.XPATH, "//span[contains(.,'Labels')]")
    LABEL_PRINTING = (By.XPATH, "//a[contains(.,' Label printing ')]")
    LABEL_TEMPLATE = (By.XPATH, "//a[contains(.,' Label template ')]")
    
    
    


class BulletinPageLocators():
    ADD = (By.CSS_SELECTOR, "a.btn")
    SUBJECT = (By.XPATH, "//label[text()='Subject']/following-sibling::div//input")
    MESSAGE = (By.XPATH, "//label[text()='Message']/following-sibling::div//textarea")
    FILTER_INPUT = (By.XPATH, "//label[text()=' Supplier list ']/following-sibling::div//input[@type='text']")
    FILTER_CHOICE = (By.XPATH, "//span[@class='v-list-item__mask']")
    SUBMIT = (By.XPATH, "//button[@type='submit']")
    ATTACH = (By.CSS_SELECTOR, ".d-none")
    DATE_FROM = (By.XPATH, "//label[text()='Date (UTC)']/following-sibling::div//input")
    DATE_TILL = (By.XPATH, "//label[text()='Valid till (UTC)']/following-sibling::div//input")
    TRASH_BUTTON = (By.CSS_SELECTOR, ".mdi-delete")
    DELETE_BUTTON = (By.XPATH, "//span[text()=' Delete ']")
    ALL_NEW = (By.XPATH, "//div[text()=' All ']")
    SUP01_NEW = (By.XPATH, "//div[text()=' SUP01 ']")
    SUP02_NEW = (By.XPATH, "//div[text()=' SUP02 ']")
    PAST = (By.XPATH, "//span[text()=' Past ']")
    ALL_PAST = (By.XPATH, "//div[text()=' All_old ']")
    SUP01_PAST = (By.XPATH, "//div[text()=' SUP01_old ']")
    SUP02_PAST = (By.XPATH, "//div[text()=' SUP02_old ']")
    PENCIL = (By.CSS_SELECTOR, ".mdi-pencil")
    MESSAGE_EDIT = (By.XPATH, "//label[text()=' Message ']/following-sibling::div//textarea")
    EMPTY_LIST = (By.XPATH, "//div[text()='No data available']")

class UsersPageLocators():
    ADD = (By.XPATH, "//span[text()=' Add ']")
    EMAIL = (By.XPATH, "//label[text()='E-mail']/following-sibling::div//input")
    NAME = (By.XPATH, "//label[text()=' Name ']/following-sibling::div//input")
    ROLES_LIST = (By.XPATH, "//label[text()=' Role ']/following-sibling::div//i")
    GSDB = (By.XPATH, "//label[text()=' ASDB ']/following-sibling::div//input")
    SUBMIT = (By.XPATH, "//button[@type='submit']")
    USERS_LIST = (By.XPATH, "//table/tbody/tr")

class SuppliersPageLocators():
    FILTER = (By.XPATH, "//span[text()=' Filter ']")
    SHIPPING_ADDRESS = (By.XPATH, "//span[text()=' Shipping Address ']/following-sibling::div//input")
    PHYSICAL_ADDRESS = (By.XPATH, "//span[text()=' Physical Address ']/following-sibling::div//input")
    BILLING_ADDRESS = (By.XPATH, "//span[text()=' Billing Address ']/following-sibling::div//input")
    TIMEZONE = (By.XPATH, "//span[text()=' Shipping timezone ']/following-sibling::div//input")
    LANG = (By.XPATH, "//span[text()=' Language ']/following-sibling::div//i")
    ADD = (By.XPATH, "//span[text()=' Add ']")
    SAVE = (By.XPATH, "//span[text()=' Save ']")
    SFTP = (By.XPATH, "//span[text()=' Change SFTP Password ']")
    
class ASNPageLocators():
    CREATE = (By.XPATH, "//span[text()=' Create ']")
    UPLOAD = (By.XPATH, "//span[text()=' upload ']")
    CARRIER = (By.XPATH, "//label[text()=' Carrier ']/following-sibling::div//input")
    PLANTLIST = (By.XPATH, "//label[text()=' Plant ']/following-sibling::div//i")
    CONTAINER = (By.XPATH, "//label[text()=' Container number ']/following-sibling::div//input")
    TRANS = (By.XPATH, "//label[text()=' Transportation mode* ']/following-sibling::div//input")
    SHIP_DATE = (By.XPATH, "//label[text()=' Shipping date ']/following-sibling::div//input")
    BOL = (By.XPATH, "//label[text()=' Bill of lading ']/following-sibling::div//input")
    FREIGHT = (By.XPATH, "//label[text()=' Freight bill number ']/following-sibling::div//input")
    NET_WEIGHT = (By.XPATH, "//label[text()=' Net weight, kg ']/following-sibling::div//input")
    GROSS_WEIGHT = (By.XPATH, "//label[text()=' Gross weight, kg ']/following-sibling::div//input")
    CONTRACT = (By.XPATH, "//label[text()=' Contract ']/following-sibling::div//input")
    ADD_PARTS = (By.XPATH, "(//span[text()=' Add '])[1]")
    ADD_PACKS = (By.XPATH, "(//span[text()=' Add '])[2]")
    SUBMIT = (By.XPATH, "//button[text()=' Create ']")
    PARTS_PART = (By.XPATH, "//label[text()=' Part number ']/following-sibling::div//input")
    PARTS_QTY = (By.XPATH, "//label[text()=' Quantity sent ']/following-sibling::div//input")
    PARTS_TOTAL = (By.XPATH, "//label[text()=' Previous total quantity ']/following-sibling::div//input")
    PARTS_UOM = (By.XPATH, "//label[text()=' Единица измерения ']/following-sibling::div//input")
    PARTS_WEIGHT = (By.XPATH, "//label[text()=' Weight, kg ']/following-sibling::div//input")
    PARTS_ORIGIN = (By.XPATH, "//label[text()=' Origin ']/following-sibling::div//input")
    PARTS_SUBMIT = (By.XPATH, "//button[@type='submit']")
    PARTS_CANCEL = (By.XPATH, "//button/span[text()=' Cancel ']")
    PACKS_PART = (By.XPATH, "//label[text()=' Part number ']/following-sibling::div//input")
    PACKS_QTY = (By.XPATH, "//label[text()=' Quantity ']/following-sibling::div//input")
    PACKS_LEVEL3 = (By.XPATH, "//label[text()=' Box serial number (level 3) ']/following-sibling::div//input")
    PACKS_LEVEL2 = (By.XPATH, "//label[text()=' Box serial number (level 2) ']/following-sibling::div//input")
    PACKS_LEVEL1 = (By.XPATH, "//label[text()=' Box serial number (level 1) ']/following-sibling::div//input")
    PACKS_TARE = (By.XPATH, "//label[text()=' Tare unit weight gross, kg ']/following-sibling::div//input")
    PACKS_SUBMIT = (By.XPATH, "//button[@type='submit']")
    PACKS_CANCEL = (By.XPATH, "//button/span[text()=' Cancel ']")

